services:
  postgres:
    image: postgres:17.7
    ports:
      - 5437:5437
    environment:
      POSTGRES_DB: blogDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
  mysql:
    container_name: mysql_container
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ./env/mysql.env

    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql

  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./docker-volumes/backend:/app
      - ./backend:/app
    env_file:
      - ./env/mysql.env
    depends_on:
      - mysql

volumes:
  docker-volumes:


